Input = require("lib/Input")
Push = require("lib/push")
STI = require("lib/sti")
require("constants")
require("utils")
require("graphics")
require("input")
require("game")
requireFolder("states")
requireFolder("objects")
requireFolder("rooms")
love.load = function()
  setupGraphics()
  setupWindow()
  input = setupInput()
  game = Game()
end
love.update = function()
  dt = love.timer.getDelta()
  return game:update()
end
love.resize = function(w, h)
  return Push:resize(w, h)
end
love.draw = function()
  Push:start()
  game:draw()
  return Push:finish()
end
